acme_admin_homepage:
    pattern:  /admin/
    defaults: { _controller: AcmeAdminBundle:Default:index }
acme_admin_gestion_homepage:
    pattern:  /admin/a/gestion/
    defaults: { _controller: AcmeAdminBundle:Default:gestion }
acme_admin_gestion_agencias:
    pattern: /admin/a/agencias/
    defaults: { _controller: AcmeAdminBundle:Agencias:list }
acme_admin_crear_agencia:
    pattern: /admin/a/agencias/create
    defaults: { _controller: AcmeAdminBundle:Agencias:create }
