parameters:
#    frontend_providers.example.class: Frontend\ProvidersBundle\Example

services:
#    frontend_providers.example:
#        class: %frontend_providers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
