parameters:
#    frontend_public.example.class: Frontend\PublicBundle\Example

services:
#    frontend_public.example:
#        class: %frontend_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
